spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    org.springframework.security: DEBUG